#include <cuda_bf16.h>
#include <cuda_runtime.h>

#include <cstdint>

namespace {

constexpr int kHeadDim = 256;
constexpr int kHalfDim = 128;

// BF16 round-to-nearest-even encodings of
// 10000 ** (-(2 * pair) / 256), generated by the ProgramIR definition.
__device__ __constant__ std::uint16_t kInverseFrequencyBf16[kHalfDim] = {
    0x3f80, 0x3f6e, 0x3f5e, 0x3f4e, 0x3f40, 0x3f33, 0x3f26, 0x3f1b,
    0x3f10, 0x3f06, 0x3ef9, 0x3ee8, 0x3ed8, 0x3ec9, 0x3ebb, 0x3eae,
    0x3ea2, 0x3e97, 0x3e8c, 0x3e82, 0x3e73, 0x3e62, 0x3e52, 0x3e44,
    0x3e36, 0x3e29, 0x3e1e, 0x3e13, 0x3e09, 0x3dfe, 0x3dec, 0x3ddc,
    0x3dcd, 0x3dbf, 0x3db1, 0x3da5, 0x3d9a, 0x3d8f, 0x3d85, 0x3d78,
    0x3d66, 0x3d56, 0x3d47, 0x3d3a, 0x3d2d, 0x3d21, 0x3d16, 0x3d0b,
    0x3d02, 0x3cf1, 0x3ce0, 0x3cd1, 0x3cc2, 0x3cb5, 0x3ca8, 0x3c9d,
    0x3c92, 0x3c88, 0x3c7c, 0x3c6b, 0x3c5a, 0x3c4b, 0x3c3d, 0x3c30,
    0x3c24, 0x3c18, 0x3c0e, 0x3c04, 0x3bf6, 0x3be5, 0x3bd5, 0x3bc6,
    0x3bb8, 0x3bab, 0x3ba0, 0x3b94, 0x3b8a, 0x3b81, 0x3b6f, 0x3b5f,
    0x3b4f, 0x3b41, 0x3b33, 0x3b27, 0x3b1b, 0x3b11, 0x3b07, 0x3afa,
    0x3ae9, 0x3ad9, 0x3aca, 0x3abc, 0x3aaf, 0x3aa3, 0x3a97, 0x3a8d,
    0x3a83, 0x3a74, 0x3a63, 0x3a53, 0x3a45, 0x3a37, 0x3a2a, 0x3a1e,
    0x3a13, 0x3a09, 0x39ff, 0x39ee, 0x39dd, 0x39ce, 0x39bf, 0x39b2,
    0x39a6, 0x399a, 0x3990, 0x3986, 0x3979, 0x3967, 0x3957, 0x3948,
    0x393a, 0x392e, 0x3921, 0x3916, 0x390c, 0x3902, 0x38f2, 0x38e1,
};

template <int Sequence, int Heads, int InputRowWidth = Heads * kHeadDim>
__device__ __forceinline__ void RopeBshdToBhsd(
    const __nv_bfloat16* input, const std::int32_t* positions,
    __nv_bfloat16* output, int block_offset = 0) {
  const int index = static_cast<int>((blockIdx.x - block_offset) * blockDim.x + threadIdx.x);
  constexpr int kPairs = Sequence * Heads * kHalfDim;
  if (index >= kPairs) return;
  const int pair = index % kHalfDim;
  const int row = index / kHalfDim;
  const int sequence = row % Sequence;
  const int head = row / Sequence;
  const int input_base = sequence * InputRowWidth + head * kHeadDim;
  const int output_base = (head * Sequence + sequence) * kHeadDim;
  const float left = __bfloat162float(input[input_base + pair]);
  const float right = __bfloat162float(input[input_base + pair + kHalfDim]);
  const float frequency =
      __uint_as_float(static_cast<unsigned>(kInverseFrequencyBf16[pair]) << 16);
  const float angle = static_cast<float>(positions[sequence]) * frequency;
  float sine = 0.0F;
  float cosine = 0.0F;
  sincosf(angle, &sine, &cosine);
  // The source evaluates BF16 cos/sin, two BF16 products, then a BF16
  // sum. Fusing those roundings into an F32 FMA changes the RoPE contract.
  const auto cos_bf16 = __float2bfloat16_rn(cosine);
  const auto sin_bf16 = __float2bfloat16_rn(sine);
  const auto left_bf16 = __float2bfloat16_rn(left);
  const auto right_bf16 = __float2bfloat16_rn(right);
  output[output_base + pair] = __hsub_rn(
      __hmul_rn(left_bf16, cos_bf16), __hmul_rn(right_bf16, sin_bf16));
  output[output_base + pair + kHalfDim] = __hadd_rn(
      __hmul_rn(left_bf16, sin_bf16), __hmul_rn(right_bf16, cos_bf16));
}

}  // namespace

extern "C" __global__ void aginfer_rope_bf16_s968_h8(
    const __nv_bfloat16* input, const std::int32_t* positions,
    __nv_bfloat16* output) {
  RopeBshdToBhsd<968, 8>(input, positions, output);
}

extern "C" __global__ void aginfer_rope_bf16_s968_h1(
    const __nv_bfloat16* input, const std::int32_t* positions,
    __nv_bfloat16* output) {
  RopeBshdToBhsd<968, 1>(input, positions, output);
}

extern "C" __global__ void aginfer_rope_bf16_s50_h8(
    const __nv_bfloat16* input, const std::int32_t* positions,
    __nv_bfloat16* output) {
  RopeBshdToBhsd<50, 8>(input, positions, output);
}

extern "C" __global__ void aginfer_rope_bf16_s50_h1(
    const __nv_bfloat16* input, const std::int32_t* positions,
    __nv_bfloat16* output) {
  RopeBshdToBhsd<50, 1>(input, positions, output);
}

// Independent block ranges: Q rotation, K rotation, prefix copies, V copy.
// The prefix remains read-only. No captured pointer is repointed and every
// suffix element is overwritten on every replay, including changed positions.
extern "C" __global__ void aginfer_qkv_rope_pack_bf16_s50_p968_h8_d256(
    const __nv_bfloat16* qkv, const std::int32_t* positions,
    const uint4* prefix_k, const uint4* prefix_v,
    __nv_bfloat16* query, __nv_bfloat16* packed_k, __nv_bfloat16* packed_v) {
  if (blockIdx.x < 200) {
    RopeBshdToBhsd<50, 8, 2560>(qkv, positions, query);
  } else if (blockIdx.x < 225) {
    RopeBshdToBhsd<50, 1, 2560>(qkv + 2048, positions, packed_k + 968 * 256, 200);
  } else if (blockIdx.x < 467) {
    constexpr int vectors = 968 * 256 / 8;
    const int index = (blockIdx.x - 225) * 256 + threadIdx.x;
    if (index < vectors) reinterpret_cast<uint4*>(packed_k)[index] = prefix_k[index];
    else if (index < 2 * vectors)
      reinterpret_cast<uint4*>(packed_v)[index - vectors] = prefix_v[index - vectors];
  } else {
    const int index = (blockIdx.x - 467) * 256 + threadIdx.x;
    if (index < 50 * 32) {
      const int row = index / 32, col = index % 32;
      reinterpret_cast<uint4*>(packed_v)[968 * 32 + index] =
          reinterpret_cast<const uint4*>(qkv)[row * 320 + 288 + col];
    }
  }
}
